version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - 8000
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONUNBUFFERED=1
      
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8000:80"
    volumes:
      - ./staticfiles:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web